Mappings:
  StageMapping:
    dev:
      domain: explorer-api.dev.sportnumerics.com
      certificate: arn:aws:acm:us-east-1:265978616089:certificate/02636181-f1d6-4cf9-8fe6-c99976b2b78a
    prodgreen:
      domain: explorer-api-green.sportnumerics.com
      certificate: arn:aws:acm:us-east-1:265978616089:certificate/02636181-f1d6-4cf9-8fe6-c99976b2b78a
    prodblue:
      domain: explorer-api-blue.sportnumerics.com
      certificate: arn:aws:acm:us-east-1:265978616089:certificate/02636181-f1d6-4cf9-8fe6-c99976b2b78a
Resources:
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - Fn::FindInMap:
              - StageMapping
              - ${opt:stage}
              - domain
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Headers:
              - Access-Control-Allow-Origin
          TargetOriginId: DefaultOrigin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          DefaultTTL: 120
          MaxTTL: 86400
        Enabled: true
        Origins:
          - DomainName:
              Fn::Join:
                - ''
                - - Ref: ApiGatewayRestApi
                  - '.execute-api.'
                  - Ref: AWS::Region
                  - '.amazonaws.com'
            OriginPath: '/${opt:stage}'
            Id: DefaultOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn:
            Fn::FindInMap:
              - StageMapping
              - ${opt:stage}
              - certificate
          SslSupportMethod: sni-only
  Domain:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - CloudfrontDistribution
            - DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: sportnumerics.com.
      Name:
        Fn::FindInMap:
          - StageMapping
          - ${opt:stage}
          - domain
      Type: A
