Mappings:
  StageMapping:
    dev:
      aliases:
        - explorer-api.dev.sportnumerics.com
      certificate: arn:aws:acm:us-east-1:265978616089:certificate/8a8d8c31-20b3-49c4-8b58-13b259064cc6
    prod:
      aliases:
        - explorer-api.sportnumerics.com
      certificate: arn:aws:acm:us-east-1:265978616089:certificate/7140c26c-5b35-4f21-b16d-695bf5a659e6
Resources:
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          Fn::FindInMap:
            - StageMapping
            - ${opt:stage}
            - aliases
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Headers:
              - Access-Control-Allow-Origin
          TargetOriginId: DefaultOrigin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          DefaultTTL: 120
          MaxTTL: 86400
        Enabled: true
        Origins:
        - DomainName:
            Fn::Join:
              - ""
              - - Ref: ApiGatewayRestApi
                - ".execute-api."
                - Ref: AWS::Region
                - ".amazonaws.com"
          OriginPath: "/${opt:stage}"
          Id: DefaultOrigin
          CustomOriginConfig:
            OriginProtocolPolicy: https-only
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn:
            Fn::FindInMap:
              - StageMapping
              - ${opt:stage}
              - certificate
          SslSupportMethod: sni-only
