service: sportnumerics-explorer-api
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
    Resource: ${self:custom.predictBucketArn}
  - Effect: "Allow"
    Action:
      - "s3:GetObject"
    Resource: "${self:custom.predictBucketArn}/*"
  environment:
    NODE_ENV: ${opt:stage}
    PREDICT_BUCKET_NAME: ${self:custom.predictBucketName}
custom:
  predictBucketName: ${cf:sportnumerics-predict-${opt:stage}.ResultsBucketName}
  predictBucketArn: "arn:aws:s3:::${cf:sportnumerics-predict-${opt:stage}.ResultsBucketName}"

resources: ${file(resources.yml)}

functions:
  divs:
    handler: handlers.divs
    events:
    - http:
        path: years/{year}
        method: get
        cors: true
  teams:
    handler: handlers.teams
    events:
    - http:
        path: years/{year}/divs/{div}
        method: get
        cors: true
  schedule:
    handler: handlers.schedule
    events:
    - http:
        path: years/{year}/teams/{id}
        method: get
        cors: true
  games:
    handler: handlers.games
    events:
    - http:
        path: years/{year}/divs/{div}/games/{date}
        method: get
        cors: true
