service: sportnumerics-explorer-api
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
    Resource: ${self:custom.resultsBucketArn}
  - Effect: "Allow"
    Action:
      - "s3:GetObject"
    Resource: "${self:custom.resultsBucketArn}/*"
  environment:
    NODE_ENV: ${opt:stage}
custom:
  resultsBucketName: "sportnumerics-predict-${opt:stage}"
  resultsBucketArn: "arn:aws:s3:::sportnumerics-predict-${opt:stage}"

resources:
  Outputs:
    ExplorerApiUrl:
      Description: Base url for sportnumerics explorer api
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - Ref: AWS::Region
            - ".amazonaws.com/"
            - ${opt:stage}
      Export:
        Name: sportnumerics-explorer-api-${opt:stage}-url

functions:
  divs:
    handler: handlers.divs
    events:
    - http:
        path: years/{year}/divs
        method: get
        cors: true
  teams:
    handler: handlers.teams
    events:
    - http:
        path: years/{year}/divs/{div}/teams
        method: get
        cors: true
  schedule:
    handler: handlers.schedule
    events:
    - http:
        path: years/{year}/divs/{div}/teams/{id}/schedule
        method: get
        cors: true
