service: sportnumerics-explorer-api
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
    Resource: ${self:custom.resultsBucketArn}
  - Effect: "Allow"
    Action:
      - "s3:GetObject"
    Resource: "${self:custom.resultsBucketArn}/*"
  - Effect: "Allow"
    Action:
      - "dynamodb:Query"
      - "dynamodb:BatchGetItem"
    Resource:
      - ${self:custom.teamsTableArn}
      - ${self:custom.teamsTableIndexesArn}
      - ${self:custom.divsTableArn}
  environment:
    NODE_ENV: ${opt:stage}
    TEAMS_TABLE_NAME: ${self:custom.teamsTableName}
    DIVS_TABLE_NAME: ${self:custom.divsTableName}
custom:
  teamsTableName: ${cf:sportnumerics-stats-${opt:stage}.TeamsTableName}
  teamsTableArn:
    Fn::Join:
    - ":"
    - - "arn:aws:dynamodb"
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.teamsTableName}
  teamsTableIndexesArn:
    Fn::Join:
      - ""
      - - ${self:custom.teamsTableArn}
        - "/index/*"
  divsTableName: ${cf:sportnumerics-stats-${opt:stage}.DivsTableName}
  divsTableArn:
    Fn::Join:
    - ":"
    - - "arn:aws:dynamodb"
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.divsTableName}
  resultsBucketName: "sportnumerics-predict-${opt:stage}"
  resultsBucketArn: "arn:aws:s3:::sportnumerics-predict-${opt:stage}"

resources: ${file(resources.yml)}

functions:
  divs:
    handler: handlers.divs
    events:
    - http:
        path: years/{year}
        method: get
        cors: true
  teams:
    handler: handlers.teams
    events:
    - http:
        path: years/{year}/divs/{div}
        method: get
        cors: true
  schedule:
    handler: handlers.schedule
    events:
    - http:
        path: years/{year}/teams/{id}
        method: get
        cors: true
